const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const {discoverJointBarriers,visibleJointColors}=require('./joint_barriers');
const {PublicSignalTracker,publicFeatures,colorTeam}=require('./public_signals');
const stadium=JSON.parse(fs.readFileSync(path.join(__dirname,'../stadiums/rs_one.hbs'),'utf8'));
const geom={...stadium.haxballrl,goal_x:1150};
assert.deepEqual(discoverJointBarriers(stadium,geom),[0,1,2,3]);
const reordered={...stadium,joints:[...stadium.joints].reverse()};
assert.deepEqual(discoverJointBarriers(reordered,geom),[2,3,4,5]);
assert.deepEqual(discoverJointBarriers({...stadium,joints:[...stadium.joints,stadium.joints[0]]},geom),[]);
const tracker=new PublicSignalTracker({auto_joints:true});
tracker.configureStadium(stadium,geom);
const discs=structuredClone(stadium.discs), joints=stadium.joints;
for(const id of tracker.jointIds)discs[joints[id].d1].pos=[...discs[joints[id].d0].pos];
const ball={pos:[200,-688],vel:[0,0],color:0x0FBCF9};
assert.equal(tracker.barrierColor(discs,[],joints,ball),-1,'collapsed lines do not reveal an owner');
discs[joints[1].d1].pos=[1149,-555];
assert.equal(tracker.barrierColor(discs,[],joints,ball),0x0000FF);
assert.equal(colorTeam(0x0FBCF9),1);assert.equal(colorTeam(0xFF3F34),0);
const players=[{team:0,pos:[0,0]},{team:1,pos:[200,-660]}];
const packet=tracker.sample(ball,players,3,15,10,tracker.barrierColor(discs,[],joints,ball));
const features=publicFeatures({ball,players,publicSignals:packet},1,geom);
assert.equal(features[1],1);assert.equal(features[5],1);
const wrong={...ball,color:0xFF3F34};
assert.equal(publicFeatures({ball:wrong,players,publicSignals:tracker.sample(wrong,players,3,15,10,0x0000FF)},1,geom)[3],1);
for(const invalid of [{...ball,vel:[1,0]},{...ball,pos:[0,0]},{...ball,pos:[200,688]},
                      {...ball,pos:[4000,-688]},{...ball,vel:[NaN,0]},{...ball,pos:[NaN,-688]}])
  assert.equal(tracker.barrierColor(discs,[],joints,invalid),-1);
discs[joints[0].d1].pos=[1149,-555];
assert.equal(tracker.barrierColor(discs,[],joints,ball),-2,'both teams extended => unknown/conflict');
assert.equal(tracker.barrierColor(discs,[],joints,{pos:[0,0],vel:[0,0]}),-1,'kickoff is not a lateral');
discs[joints[0].d1].pos=[-1149,-555];
const transparent=joints.map(j=>({...j,color:-1}));
assert.equal(tracker.barrierColor(discs,[],transparent,ball),-1);
discs[joints[1].d1].playerId=7;
assert.equal(tracker.barrierColor(discs,[],joints,ball),-1,'player endpoints cannot be public marker discs');
delete discs[joints[1].d1].playerId;
const objects=joints.map(j=>({...j,d0:discs[j.d0],d1:discs[j.d1]}));
assert.deepEqual(visibleJointColors(discs,objects,tracker.jointIds,ball,geom),['48BEF9']);
tracker.configureStadium({joints:[],discs:[]},geom);
assert.equal(tracker.barrierColor(discs,[],joints,ball),-1,'map changes clear old candidates');
assert.throws(()=>visibleJointColors(discs,joints,[-1],ball,geom),/Invalid/);
console.log('Joint discovery, public activation, conflict and map-reset tests passed');
